### ISSUE TITLE
Building library for fortran user

### ISSUE THREAD

**Issue by ShatrovOA** [ddemidov/amgcl#173]
Dear, Denis!

Can you please explain how to build library in order to use it in fortran code with mpi enabled?
I am trying to build on macos 10.15, gcc compiler 10.2 and open-mpi 3.1.
So far i got to

cmake -DAMGCL_TEST_COVERAGE=${TEST_COVERAGE}   \
          -DAMGCL_BUILD_TESTS=ON                   \
          -DAMGCL_BUILD_EXAMPLES=${BUILD_EXAMPLES} -DAMGCL_HAVE_FORTRAN=ON \
          -DAMGCL_HAVE_PYTHON=${TEST_PYTHON}       \
          -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 ..

but it doest work. 

Scanning dependencies of target test_solver_complex
[  1%] Building CXX object tests/CMakeFiles/test_solver_complex.dir/test_solver_complex.cpp.o
[  2%] Linking CXX executable test_solver_complex
Undefined symbols for architecture x86_64:
  "__ZN5boost9unit_test9ut_detail24normalize_test_case_nameB5cxx11ENS0_13basic_cstringIKcEE", referenced from:
      __GLOBAL__sub_I_test_solver_complex.cpp in test_solver_complex.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test_solver_complex.dir/build.make:104: tests/test_solver_complex] Error 1
make[1]: *** [CMakeFiles/Makefile2:351: tests/CMakeFiles/test_solver_complex.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

Thanks!

Best regards,
Shatrov Oleg.

**Comment by ddemidov** [comment]
There is currently no fortran wrapper for the MPI solvers in amgcl. You probably could start from [`fortran/amgcl.f90`](https://github.com/ddemidov/amgcl/blob/master/fortran/amgcl.f90). I would be glad to accept a pull request if you manage to do it.

Re the linking error you are having, it looks like it is coming from boost.test library. Your compile options seem to be ok, given you have defined the environment variables like `TEST_COVERAGE` or `BUILD_EXAMPLES`. I don't have access to an OSX system, but the OSX tests seem to work fine on Travis-CI: https://travis-ci.org/github/ddemidov/amgcl.

Here is a Dockerfile that builds the tests and examples including the fortran wrapper:
```dockerfile
FROM ubuntu
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -y libboost-all-dev cmake g++ gfortran git
RUN git clone https://github.com/ddemidov/amgcl
RUN cmake -Bamgcl-build -DAMGCL_BUILD_TESTS=ON -DAMGCL_BUILD_EXAMPLES=ON -DAMGCL_HAVE_FORTRAN=ON amgcl
RUN cmake --build amgcl-build
```

**Comment by ShatrovOA** [comment]
Dear, Denis!

I finally got some time and I would like to emprove fortran interfaces to AMGCL.
I noticed that you didn't put add amgcl_precond subroutines to fortran module, but they are present in lib/amgcl.cpp. Is that because they will not change preconditioner that will be used? 

Is there any way to change preconditioner from fortran?

Thanks!

Best regards,
Shatrov Oleg.

**Comment by ddemidov** [comment]
`amgcl_precond` functions are used to create preconditioner without linear solver (which should be implemented by the user in this case). Fortran interface is far from complete, it is mainly there as a wrapper example. Another example may be found here: https://github.com/ddemidov/fortran_amg_omp_ocl. 

> Is there any way to change preconditioner from fortran?

In order to change the preconditioner, you have to recreate it (this is no different from the native C++ interface), that is, destroy the current preconditioner and create the new one.
